<a href="https://colab.research.google.com/github/Safaet61-bot/Whatsapp_analyzer/blob/main/Whatsappanalyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import pandas as pd

In [5]:
import os

path = r"E:\WhatsApp Chat with Data Analyst - 2521 (Officials).txt"
print(os.path.exists(path))

False

In [8]:
from google.colab import files
uploaded = files.upload()

Saving WhatsApp Chat with Data Analyst - 2521 (Officials).txt to WhatsApp Chat with Data Analyst - 2521 (Officials).txt

In [9]:
with open("WhatsApp Chat with Data Analyst - 2521 (Officials).txt", "r", encoding="utf-8") as f:
    data = f.read()

In [10]:
print(data)

9/7/25, 10:49 - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
7/22/25, 10:58 - ~ Noor Ahmad Rayhan created group "Data Analyst - 2521 (Officials)"
9/7/25, 10:49 - You joined using this group's invite link
9/7/25, 12:18 - +880 1848-384622 joined using a group link.
9/7/25, 12:18 - +880 1764-236363 joined using a group link.
9/7/25, 12:18 - +880 1799-886070 joined using a group link.
9/7/25, 12:18 - +880 1303-708022 joined using a group link.
9/7/25, 12:18 - +880 1844-537948 joined using a group link.
9/7/25, 16:46 - +353 89 956 1965 joined using a group link.
9/7/25, 16:46 - +880 1922-666471 joined using a group link.
9/7/25, 16:46 - +880 1913-098955 joined using a group link.
9/7/25, 18:18 - +880 1788-820163 joined using a group link.
9/8/25, 10:17 - +880 1991-989466 joined using a group link.
9/8/25, 10:17 - +880 1791-035503 joined using a group link.
9/8/25, 10:18 - +880 1787-380148 joined using a group link.
9/8/25, 10:18 - +880 1703-699859 joined using a group link.
9/8/25, 10:18 - +880 1537-413648 joined using a group link.
9/8/25, 11:07 - ~ Noor Ahmad Rayhan added ~ Debasish Nag
9/8/25, 11:08 - +880 1751-087380: রিমাইন্ডার 📢
🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর প্রথম ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
Data Solution 360
9/8/25, 15:19 - +880 1711-720153: আপনাদের মাইক্রোসফট এক্সেল এর প্রথম ক্লাস এর Class Materials Google Classroom এ Upload করা হয়েছে । ক্লাস শুরু হবার আগেই আপনার পিসিতে Download করে রাখুন। ক্লাস চলাকালিন সময়ে আপনারা আমার সাথে Practice করতে পারবেন। ধন্যবাদ।
9/8/25, 15:22 - +880 1711-720153: <Media omitted>
9/8/25, 15:46 - +880 1789-073959 joined using a group link.
9/8/25, 16:22 - +880 1773-153335 joined using a group link.
9/8/25, 16:22 - +880 1613-911208 joined using a group link.
9/8/25, 16:49 - +880 1952-058563 joined using a group link.
9/8/25, 17:01 - +880 1647-612923 added +880 1828-117105 and +880 1915-055296
9/8/25, 19:55 - Shagor Vaia: রিমাইন্ডার 📢
🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর প্রথম ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
Data Solution 360
9/8/25, 19:53 - +880 1944-790016 joined using a group link.
9/8/25, 19:54 - +880 1618-358323 joined using a group link.
9/8/25, 19:54 - +880 1878-374844 joined using a group link.
9/8/25, 19:54 - +880 1623-542890 joined using a group link.
9/9/25, 10:20 - +880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-01 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।

Link for Class-01:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAyOTY5MDI0NTQ2/details

যারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7

(*বি:দ্র:* আপনাদের প্রতিটা ক্লাস রেকর্ড, ক্লাস শেষ হওয়ার ২৪ ঘণ্টার মধ্যে গুগল ক্লাসরুমে আপলোড করা হবে)
9/9/25, 11:15 - Shagor Vaia: <Media omitted>
9/9/25, 11:49 - Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners

প্রিয় শিক্ষার্থীবৃন্দ,

আপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!

🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!
আমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।

💡 Microsoft 365-এ যা যা পাচ্ছেন:

✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)

✅ PowerPoint Designer এবং Premium Templates

✅ Word Editor, Resume Assistant, Citation Tools

✅ Microsoft Teams


🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—

📞 WhatsApp: 01955723327
(Please mention your name and batch when messaging)

শুভকামনায়,
Data Solution 360 টিম
9/10/25, 10:52 - Shagor Vaia added +880 1737-308965
9/11/25, 11:55 - +880 1647-612923 added ~ Philemon Das, +880 1576-554178, +880 1711-067619, +880 1744-990314, +880 1788-890875, and +880 1796-526560
9/11/25, 12:10 - +880 1819-309117 joined using a group link.
9/12/25, 14:24 - +880 1711-720153: 🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ২য় ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
Data Solution 360
9/12/25, 19:36 - +880 1711-720153: 🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ২য় ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
Data Solution 360
9/13/25, 10:38 - +880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-02 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।

Link for Class-02:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODA1OTAyNTc1MjQ3/details

যারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7
9/13/25, 15:26 - Shagor Vaia added +880 1775-649330
9/14/25, 14:52 - +880 1857-688098 joined using a group link.
9/15/25, 11:32 - +880 1711-720153: This message was deleted
9/15/25, 11:37 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৩য় ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/15/25, 19:51 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৩য় ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/16/25, 00:38 - +880 1580-375504 joined using a group link.
9/16/25, 11:52 - +880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-03 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।

Link for Class-03:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAzMTUyNTc2MTM2/details

যারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7
9/17/25, 12:56 - Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners

প্রিয় শিক্ষার্থীবৃন্দ,

আপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!

🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!
আমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।

💡 Microsoft 365-এ যা যা পাচ্ছেন:

✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)

✅ PowerPoint Designer এবং Premium Templates

✅ Word Editor, Resume Assistant, Citation Tools

✅ Microsoft Teams


🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—

📞 WhatsApp: 01955723327
(Please mention your name and batch when messaging)

শুভকামনায়,
Data Solution 360 টিম
9/19/25, 07:48 - +880 1744-787373 joined using a group link.
9/19/25, 13:31 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/19/25, 19:18 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/19/25, 20:42 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/20/25, 11:31 - +880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-04 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।

Link for Class-04:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAzMjk0NTI5MDMw/details

যারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7
9/21/25, 10:43 - +880 1711-720153: https://forms.gle/Ltni1DoRhHL4Pg5v9
9/21/25, 13:33 - Excel 365: 📢 Dear Learners,

আমাদের প্রতিটি ব্যাচে সাপোর্ট ইন্সট্রাক্টররা আপনাদের পাশে আছেন।
যদি প্র্যাকটিস করতে গিয়ে কোন ধরনের সাপোর্ট বা হেল্পের প্রয়োজন হয়, তাহলে নিচের Support Team Member দের সাথে যোগাযোগ করতে পারেন 👇

📞 01745489812 – Md Sabbir Hossain (Specially Python, SQL, Statistics)
📞 01826708635 – Jannatul Mawa (Specially Python, SQL, Statistics)
📞 01624764617 – Habib Bhuiyan (Specially Excel & Power BI)
📞 01957546308 – Saiful Islam Sagor (Excel and Website Related Help)
📞 01775649330 – AB Siddique (Excel and Power BI Help)
📞 01647612923 – Onnesha Akter Nova (Excel and Power BI Help)
📞 01689904841 – Tasmin Akter Tripty (Power BI, SQL, and Excel Help)
📞 01915-966721 – Md. Masum Billah (Power BI, SQL, and Excel Help)

👉 আপনারা প্রয়োজন অনুযায়ী সংশ্লিষ্ট Support Instructor কে সকাল ৯ টা থেকে রাত ১০ টার মধ্যে নক করবেন। কোন কারনে আপনার মেসেজ এর রিপ্লে পেতে লেট হলে সারাসরি ফোন দিবেন

ধন্যবাদ।
Data Solution 360 – Technical Support Team
9/21/25, 13:33 - Excel 365 pinned a message
9/22/25, 16:46 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৫ম ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/22/25, 19:54 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৫ম ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/23/25, 11:45 - +880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-05 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।

Link for Class-05:
https://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODA4MDkyMTU2Mzg4/details
9/25/25, 11:44 - Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners

প্রিয় শিক্ষার্থীবৃন্দ,

আপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!

🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!
আমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।

💡 Microsoft 365-এ যা যা পাচ্ছেন:

✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)

✅ PowerPoint Designer এবং Premium Templates

✅ Word Editor, Resume Assistant, Citation Tools

✅ Microsoft Teams


🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—

📞 WhatsApp: 01955723327
(Please mention your name and batch when messaging)

শুভকামনায়,
Data Solution 360 টিম
9/26/25, 14:37 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৬ষ্ঠ ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨
9/26/25, 19:51 - +880 1711-720153: রিমাইন্ডার 📢
🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৬ষ্ঠ ক্লাস শুরু হবে।
📍 প্ল্যাটফর্ম: Google Meet
🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq
📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।
শুভ কামনা রইল! ✨

In [20]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [21]:
messages = re.split(pattern,data)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.\n',
 '~\u202fNoor Ahmad Rayhan created group "Data Analyst - 2521 (Officials)"\n',
 "You joined using this group's invite link\n",
 '+880 1848-384622 joined using a group link.\n',
 '+880 1764-236363 joined using a group link.\n',
 '+880 1799-886070 joined using a group link.\n',
 '+880 1303-708022 joined using a group link.\n',
 '+880 1844-537948 joined using a group link.\n',
 '+353 89 956 1965 joined using a group link.\n',
 '+880 1922-666471 joined using a group link.\n',
 '+880 1913-098955 joined using a group link.\n',
 '+880 1788-820163 joined using a group link.\n',
 '+880 1991-989466 joined using a group link.\n',
 '+880 1791-035503 joined using a group link.\n',
 '+880 1787-380148 joined using a group link.\n',
 '+880 1703-699859 joined using a group link.\n',
 '+880 1537-413648 joined using a group link.\n',
 '~\u202fNoor Ahmad Rayhan added ~\u202fDebasish Nag\n',
 '+880 1751-087380: রিমাইন্ডার 📢  \n🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর প্রথম ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\nData\xa0Solution\xa0360\n',
 '+880 1711-720153: আপনাদের মাইক্রোসফট এক্সেল এর প্রথম ক্লাস এর Class Materials Google Classroom এ Upload করা হয়েছে । ক্লাস শুরু হবার আগেই আপনার পিসিতে Download করে রাখুন। ক্লাস চলাকালিন সময়ে আপনারা আমার সাথে Practice করতে পারবেন। ধন্যবাদ।\n',
 '+880 1711-720153: <Media omitted>\n',
 '+880 1789-073959 joined using a group link.\n',
 '+880 1773-153335 joined using a group link.\n',
 '+880 1613-911208 joined using a group link.\n',
 '+880 1952-058563 joined using a group link.\n',
 '+880 1647-612923 added +880 1828-117105 and +880 1915-055296\n',
 'Shagor Vaia: রিমাইন্ডার 📢  \n🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর প্রথম ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\nData\xa0Solution\xa0360\n',
 '+880 1944-790016 joined using a group link.\n',
 '+880 1618-358323 joined using a group link.\n',
 '+880 1878-374844 joined using a group link.\n',
 '+880 1623-542890 joined using a group link.\n',
 '+880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-01 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।\n\nLink for Class-01: \nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAyOTY5MDI0NTQ2/details\n\nযারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:\nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7\n\n(*বি:দ্র:* আপনাদের প্রতিটা ক্লাস রেকর্ড, ক্লাস শেষ হওয়ার ২৪ ঘণ্টার মধ্যে গুগল ক্লাসরুমে আপলোড করা হবে)\n',
 'Shagor Vaia: <Media omitted>\n',
 'Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners\n\nপ্রিয় শিক্ষার্থীবৃন্দ,\n\nআপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!\n\n🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!\nআমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।\n\n💡 Microsoft 365-এ যা যা পাচ্ছেন:\n\n✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)\n\n✅ PowerPoint Designer এবং Premium Templates\n\n✅ Word Editor, Resume Assistant, Citation Tools\n\n✅ Microsoft Teams\n\n\n🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—\n\n📞 WhatsApp: 01955723327\n(Please mention your name and batch when messaging)\n\nশুভকামনায়,\nData Solution 360 টিম\n',
 'Shagor Vaia added +880 1737-308965\n',
 '+880 1647-612923 added ~\u202fPhilemon Das, +880 1576-554178, +880 1711-067619, +880 1744-990314, +880 1788-890875, and +880 1796-526560\n',
 '+880 1819-309117 joined using a group link.\n',
 '+880 1711-720153: 🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ২য় ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\nData Solution 360\n',
 '+880 1711-720153: 🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ২য় ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\nData Solution 360\n',
 '+880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-02 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।\n\nLink for Class-02: \nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODA1OTAyNTc1MjQ3/details\n\nযারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:\nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7\n',
 'Shagor Vaia added +880 1775-649330\n',
 '+880 1857-688098 joined using a group link.\n',
 '+880 1711-720153: This message was deleted\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৩য় ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত ০৯:৩০ মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৩য় ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1580-375504 joined using a group link.\n',
 '+880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-03 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।\n\nLink for Class-03: \nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAzMTUyNTc2MTM2/details\n\nযারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:\nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7\n',
 'Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners\n\nপ্রিয় শিক্ষার্থীবৃন্দ,\n\nআপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!\n\n🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!\nআমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।\n\n💡 Microsoft 365-এ যা যা পাচ্ছেন:\n\n✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)\n\n✅ PowerPoint Designer এবং Premium Templates\n\n✅ Word Editor, Resume Assistant, Citation Tools\n\n✅ Microsoft Teams\n\n\n🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—\n\n📞 WhatsApp: 01955723327\n(Please mention your name and batch when messaging)\n\nশুভকামনায়,\nData Solution 360 টিম\n',
 '+880 1744-787373 joined using a group link.\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:00 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৪র্থ  ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-04 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।\n\nLink for Class-04: \nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODAzMjk0NTI5MDMw/details\n\nযারা এখনো গুগল ক্লাসরুমে যুক্ত হননি, নিচের লিংক থেকে যুক্ত হওয়ার জন্য অনুরোধ করা হচ্ছে:\nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz?cjc=ad6haeq7\n',
 '+880 1711-720153: https://forms.gle/Ltni1DoRhHL4Pg5v9\n',
 'Excel 365: 📢 Dear Learners,\n\nআমাদের প্রতিটি ব্যাচে সাপোর্ট ইন্সট্রাক্টররা আপনাদের পাশে আছেন।\nযদি প্র্যাকটিস করতে গিয়ে কোন ধরনের সাপোর্ট বা হেল্পের প্রয়োজন হয়, তাহলে নিচের Support Team Member দের সাথে যোগাযোগ করতে পারেন 👇\n\n📞 01745489812 – Md Sabbir Hossain (Specially Python, SQL, Statistics)\n📞 01826708635 – Jannatul Mawa (Specially Python, SQL, Statistics)\n📞 01624764617 – Habib Bhuiyan (Specially Excel & Power BI)\n📞 01957546308 – Saiful Islam Sagor (Excel and Website Related Help)\n📞 01775649330 – AB Siddique (Excel and Power BI Help)\n📞 01647612923 – Onnesha Akter Nova (Excel and Power BI Help)\n📞 01689904841 – Tasmin Akter Tripty (Power BI, SQL, and Excel Help)\n📞 01915-966721 – Md. Masum Billah (Power BI, SQL, and Excel Help)\n\n👉 আপনারা প্রয়োজন অনুযায়ী সংশ্লিষ্ট Support Instructor কে সকাল ৯ টা থেকে রাত ১০ টার মধ্যে নক করবেন। কোন কারনে আপনার মেসেজ এর রিপ্লে পেতে লেট হলে সারাসরি ফোন দিবেন\n\nধন্যবাদ।\nData Solution 360 – Technical Support Team\n',
 'Excel 365 pinned a message\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৫ম ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৫ম ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1751-087380: আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনাদের Class-05 রেকর্ড ভিডিও গুগল ক্লাসরুমে আপলোড করা হয়েছে।\n\nLink for Class-05: \nhttps://classroom.google.com/c/Nzk5NzY3MjI2Njkz/p/ODA4MDkyMTU2Mzg4/details\n',
 'Excel 365: 📢 Microsoft 365 Subscription – Special Offer for Our Learners\n\nপ্রিয় শিক্ষার্থীবৃন্দ,\n\nআপনারা যারা Excel, Word কিংবা PowerPoint নিয়ে নিয়মিত কাজ করছেন—তাদের জন্য রয়েছে একটি দারুণ সুযোগ!\n\n🔐 Microsoft 365-এর এক বছরের সাবস্ক্রিপশন এখন মাত্র ৩৫০ টাকায়!\nআমাদের একটি বিশ্বস্ত ও ট্রাস্টেড সোর্স থেকে আমরা এটি প্রোভাইড করছি, যেটি আপনার একাউন্টকে সুরক্ষিত রাখবে এবং নির্বিঘ্নে ব্যবহার করতে পারবেন পুরো এক বছর।\n\n💡 Microsoft 365-এ যা যা পাচ্ছেন:\n\n✅ Excel-এর Advanced Features (Smart Fill, Forecast, Data Types, Ideas)\n\n✅ PowerPoint Designer এবং Premium Templates\n\n✅ Word Editor, Resume Assistant, Citation Tools\n\n✅ Microsoft Teams\n\n\n🎯 যারা Microsoft 365 নিতে আগ্রহী, তারা আমার সাথে WhatsApp-এ সরাসরি যোগাযোগ করুন নিচের নাম্বারে—\n\n📞 WhatsApp: 01955723327\n(Please mention your name and batch when messaging)\n\nশুভকামনায়,\nData Solution 360 টিম\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৬ষ্ঠ ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n',
 '+880 1711-720153: রিমাইন্ডার 📢  \n🕤 আজ রাত 0৯:৩0 মিনিটে আপনাদের 📊 মাইক্রোসফট এক্সেল এর ৬ষ্ঠ ক্লাস শুরু হবে।\n📍 প্ল্যাটফর্ম: Google Meet\n🔗 Class Link: https://meet.google.com/kpa-tsyg-yxq\n📚 সবাইকে সময়মতো ক্লাসে উপস্থিত থাকার জন্য অনুরোধ করছি।\nশুভ কামনা রইল! ✨\n']

In [17]:
print("Total messages:", len(messages))

Total messages: 0

In [35]:
dates = re.findall(pattern, data)

In [36]:
dates

['9/7/25, 10:49 - ',
 '7/22/25, 10:58 - ',
 '9/7/25, 10:49 - ',
 '9/7/25, 12:18 - ',
 '9/7/25, 12:18 - ',
 '9/7/25, 12:18 - ',
 '9/7/25, 12:18 - ',
 '9/7/25, 12:18 - ',
 '9/7/25, 16:46 - ',
 '9/7/25, 16:46 - ',
 '9/7/25, 16:46 - ',
 '9/7/25, 18:18 - ',
 '9/8/25, 10:17 - ',
 '9/8/25, 10:17 - ',
 '9/8/25, 10:18 - ',
 '9/8/25, 10:18 - ',
 '9/8/25, 10:18 - ',
 '9/8/25, 11:07 - ',
 '9/8/25, 11:08 - ',
 '9/8/25, 15:19 - ',
 '9/8/25, 15:22 - ',
 '9/8/25, 15:46 - ',
 '9/8/25, 16:22 - ',
 '9/8/25, 16:22 - ',
 '9/8/25, 16:49 - ',
 '9/8/25, 17:01 - ',
 '9/8/25, 19:55 - ',
 '9/8/25, 19:53 - ',
 '9/8/25, 19:54 - ',
 '9/8/25, 19:54 - ',
 '9/8/25, 19:54 - ',
 '9/9/25, 10:20 - ',
 '9/9/25, 11:15 - ',
 '9/9/25, 11:49 - ',
 '9/10/25, 10:52 - ',
 '9/11/25, 11:55 - ',
 '9/11/25, 12:10 - ',
 '9/12/25, 14:24 - ',
 '9/12/25, 19:36 - ',
 '9/13/25, 10:38 - ',
 '9/13/25, 15:26 - ',
 '9/14/25, 14:52 - ',
 '9/15/25, 11:32 - ',
 '9/15/25, 11:37 - ',
 '9/15/25, 19:51 - ',
 '9/16/25, 00:38 - ',
 '9/16/25, 11:52 - ',
 '9/17/25, 12:56 - ',
 '9/19/25, 07:48 - ',
 '9/19/25, 13:31 - ',
 '9/19/25, 19:18 - ',
 '9/19/25, 20:42 - ',
 '9/20/25, 11:31 - ',
 '9/21/25, 10:43 - ',
 '9/21/25, 13:33 - ',
 '9/21/25, 13:33 - ',
 '9/22/25, 16:46 - ',
 '9/22/25, 19:54 - ',
 '9/23/25, 11:45 - ',
 '9/25/25, 11:44 - ',
 '9/26/25, 14:37 - ',
 '9/26/25, 19:51 - ']

In [39]:
# Make sure the column is string type first
df['date'] = df['date'].astype(str)

# Convert to datetime safely; invalid parsing becomes NaT
df['date'] = pd.to_datetime(df['date'].str.strip(' -'), errors='coerce', dayfirst=True)

df.head()

                                        user_message date
0  Messages and calls are end-to-end encrypted. O...  NaT
1  ~ Noor Ahmad Rayhan created group "Data Analys...  NaT
2        You joined using this group's invite link\n  NaT
3      +880 1848-384622 joined using a group link.\n  NaT
4      +880 1764-236363 joined using a group link.\n  NaT

In [44]:
# Extract timestamp and message from each line
lines = data.split('\n')
dates_and_messages = []
for line in lines:
    match = re.match(pattern, line)
    if match:
        date = match.group(0).strip(' -')
        message = line[match.end():].strip()
        dates_and_messages.append([date, message])

# Create a DataFrame from the extracted data
df = pd.DataFrame(dates_and_messages, columns=['date', 'user_message'])

# Convert the 'date' column to datetime objects
df['date'] = pd.to_datetime(df['date'], errors='coerce', dayfirst=True)

/tmp/ipython-input-303516498.py:15: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'], errors='coerce', dayfirst=True)

In [47]:
df = df[['user_message', 'date']]
display(df.head())

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-07-09 10:49:00
1  ~ Noor Ahmad Rayhan created group "Data Analys... 2025-07-22 10:58:00
2          You joined using this group's invite link 2025-07-09 10:49:00
3        +880 1848-384622 joined using a group link. 2025-07-09 12:18:00
4        +880 1764-236363 joined using a group link. 2025-07-09 12:18:00

In [48]:
# separate users and messages

users =[]
messages = []
for message in df['user_message']:
    entry=re.split('([\w\W]+?):\s', message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])
df['users'] = users
df['messages'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

<>:6: SyntaxWarning: invalid escape sequence '\w'
<>:6: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-1594157857.py:6: SyntaxWarning: invalid escape sequence '\w'
  entry=re.split('([\w\W]+?):\s', message)

,date,users,messages
0,2025-07-09 10:49:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2025-07-22 10:58:00,group_notification,"~ Noor Ahmad Rayhan created group ""Data Analys..."
2,2025-07-09 10:49:00,group_notification,You joined using this group's invite link
3,2025-07-09 12:18:00,group_notification,+880 1848-384622 joined using a group link.
4,2025-07-09 12:18:00,group_notification,+880 1764-236363 joined using a group link.

In [40]:
print(df.columns)

Index(['user_message', 'date'], dtype='object')

In [49]:
df['month'] = df['date'].dt.month_name()

In [50]:
df['day'] = df['date'].dt.day

In [51]:
df['hour'] = df['date'].dt.hour

In [52]:
df['minute'] = df['date'].dt.minute

In [53]:
df.head()

,date,users,messages,month,day,hour,minute
0,2025-07-09 10:49:00,group_notification,Messages and calls are end-to-end encrypted. O...,July,9,10,49
1,2025-07-22 10:58:00,group_notification,"~ Noor Ahmad Rayhan created group ""Data Analys...",July,22,10,58
2,2025-07-09 10:49:00,group_notification,You joined using this group's invite link,July,9,10,49
3,2025-07-09 12:18:00,group_notification,+880 1848-384622 joined using a group link.,July,9,12,18
4,2025-07-09 12:18:00,group_notification,+880 1764-236363 joined using a group link.,July,9,12,18

In [54]:
df['messages'] = df['messages'].replace('\n','', regex=True)
df['messages'] = df['messages'].replace('\t','', regex=True)

In [55]:
df['messages'].head(5)

0    Messages and calls are end-to-end encrypted. O...
1    ~ Noor Ahmad Rayhan created group "Data Analys...
2            You joined using this group's invite link
3          +880 1848-384622 joined using a group link.
4          +880 1764-236363 joined using a group link.
Name: messages, dtype: object

In [56]:
df.drop('date', inplace=True, axis=1)

In [57]:
df.head()

,users,messages,month,day,hour,minute
0,group_notification,Messages and calls are end-to-end encrypted. O...,July,9,10,49
1,group_notification,"~ Noor Ahmad Rayhan created group ""Data Analys...",July,22,10,58
2,group_notification,You joined using this group's invite link,July,9,10,49
3,group_notification,+880 1848-384622 joined using a group link.,July,9,12,18
4,group_notification,+880 1764-236363 joined using a group link.,July,9,12,18

In [58]:
words =[]
for message in df['messages']:
    words.extend(message.split())
print(words)
print(len(words))

['Messages', 'and', 'calls', 'are', 'end-to-end', 'encrypted.', 'Only', 'people', 'in', 'this', 'chat', 'can', 'read,', 'listen', 'to,', 'or', 'share', 'them.', 'Learn', 'more.', '~', 'Noor', 'Ahmad', 'Rayhan', 'created', 'group', '"Data', 'Analyst', '-', '2521', '(Officials)"', 'You', 'joined', 'using', 'this', "group's", 'invite', 'link', '+880', '1848-384622', 'joined', 'using', 'a', 'group', 'link.', '+880', '1764-236363', 'joined', 'using', 'a', 'group', 'link.', '+880', '1799-886070', 'joined', 'using', 'a', 'group', 'link.', '+880', '1303-708022', 'joined', 'using', 'a', 'group', 'link.', '+880', '1844-537948', 'joined', 'using', 'a', 'group', 'link.', '+353', '89', '956', '1965', 'joined', 'using', 'a', 'group', 'link.', '+880', '1922-666471', 'joined', 'using', 'a', 'group', 'link.', '+880', '1913-098955', 'joined', 'using', 'a', 'group', 'link.', '+880', '1788-820163', 'joined', 'using', 'a', 'group', 'link.', '+880', '1991-989466', 'joined', 'using', 'a', 'group', 'link.', '+880', '1791-035503', 'joined', 'using', 'a', 'group', 'link.', '+880', '1787-380148', 'joined', 'using', 'a', 'group', 'link.', '+880', '1703-699859', 'joined', 'using', 'a', 'group', 'link.', '+880', '1537-413648', 'joined', 'using', 'a', 'group', 'link.', '~', 'Noor', 'Ahmad', 'Rayhan', 'added', '~', 'Debasish', 'Nag', 'রিমাইন্ডার', '📢', 'আপনাদের', 'মাইক্রোসফট', 'এক্সেল', 'এর', 'প্রথম', 'ক্লাস', 'এর', 'Class', 'Materials', 'Google', 'Classroom', 'এ', 'Upload', 'করা', 'হয়েছে', '।', 'ক্লাস', 'শুরু', 'হবার', 'আগেই', 'আপনার', 'পিসিতে', 'Download', 'করে', 'রাখুন।', 'ক্লাস', 'চলাকালিন', 'সময়ে', 'আপনারা', 'আমার', 'সাথে', 'Practice', 'করতে', 'পারবেন।', 'ধন্যবাদ।', '<Media', 'omitted>', '+880', '1789-073959', 'joined', 'using', 'a', 'group', 'link.', '+880', '1773-153335', 'joined', 'using', 'a', 'group', 'link.', '+880', '1613-911208', 'joined', 'using', 'a', 'group', 'link.', '+880', '1952-058563', 'joined', 'using', 'a', 'group', 'link.', '+880', '1647-612923', 'added', '+880', '1828-117105', 'and', '+880', '1915-055296', 'রিমাইন্ডার', '📢', '+880', '1944-790016', 'joined', 'using', 'a', 'group', 'link.', '+880', '1618-358323', 'joined', 'using', 'a', 'group', 'link.', '+880', '1878-374844', 'joined', 'using', 'a', 'group', 'link.', '+880', '1623-542890', 'joined', 'using', 'a', 'group', 'link.', 'আসসালামু', 'আলাইকুম,', 'আশা', 'করি', 'সবাই', 'ভালো', 'আছেন।', 'আপনাদের', 'Class-01', 'রেকর্ড', 'ভিডিও', 'গুগল', 'ক্লাসরুমে', 'আপলোড', 'করা', 'হয়েছে।', '<Media', 'omitted>', '📢', 'Microsoft', '365', 'Subscription', '–', 'Special', 'Offer', 'for', 'Our', 'Learners', 'Shagor', 'Vaia', 'added', '+880', '1737-308965', '+880', '1647-612923', 'added', '~', 'Philemon', 'Das,', '+880', '1576-554178,', '+880', '1711-067619,', '+880', '1744-990314,', '+880', '1788-890875,', 'and', '+880', '1796-526560', '+880', '1819-309117', 'joined', 'using', 'a', 'group', 'link.', '🕤', 'আজ', 'রাত', '০৯:৩০', 'মিনিটে', 'আপনাদের', '📊', 'মাইক্রোসফট', 'এক্সেল', 'এর', '২য়', 'ক্লাস', 'শুরু', 'হবে।', '🕤', 'আজ', 'রাত', '০৯:৩০', 'মিনিটে', 'আপনাদের', '📊', 'মাইক্রোসফট', 'এক্সেল', 'এর', '২য়', 'ক্লাস', 'শুরু', 'হবে।', 'আসসালামু', 'আলাইকুম,', 'আশা', 'করি', 'সবাই', 'ভালো', 'আছেন।', 'আপনাদের', 'Class-02', 'রেকর্ড', 'ভিডিও', 'গুগল', 'ক্লাসরুমে', 'আপলোড', 'করা', 'হয়েছে।', 'Shagor', 'Vaia', 'added', '+880', '1775-649330', '+880', '1857-688098', 'joined', 'using', 'a', 'group', 'link.', 'This', 'message', 'was', 'deleted', 'রিমাইন্ডার', '📢', 'রিমাইন্ডার', '📢', '+880', '1580-375504', 'joined', 'using', 'a', 'group', 'link.', 'আসসালামু', 'আলাইকুম,', 'আশা', 'করি', 'সবাই', 'ভালো', 'আছেন।', 'আপনাদের', 'Class-03', 'রেকর্ড', 'ভিডিও', 'গুগল', 'ক্লাসরুমে', 'আপলোড', 'করা', 'হয়েছে।', '📢', 'Microsoft', '365', 'Subscription', '–', 'Special', 'Offer', 'for', 'Our', 'Learners', '+880', '1744-787373', 'joined', 'using', 'a', 'group', 'link.', 'রিমাইন্ডার', '📢', 'রিমাইন্ডার', '📢', 'রিমাইন্ডার', '📢', 'আসসালামু', 'আলাইকুম,', 'আশা', 'করি', 'সবাই', 'ভালো', 'আছেন।', 'আপনাদের', 'Class-04', 'রেকর্ড', 'ভিডিও', 'গুগল', 'ক্লাসরুমে', 'আপলোড', 'করা', 'হয়েছে।', 'https://forms.gle/Ltni1DoRhHL4Pg5v9', '📢', 'Dear', 'Learners,', 'Excel', '365', 'pinned', 'a', 'message', 'রিমাইন্ডার', '📢', 'রিমাইন্ডার', '📢', 'আসসালামু', 'আলাইকুম,', 'আশা', 'করি', 'সবাই', 'ভালো', 'আছেন।', 'আপনাদের', 'Class-05', 'রেকর্ড', 'ভিডিও', 'গুগল', 'ক্লাসরুমে', 'আপলোড', 'করা', 'হয়েছে।', '📢', 'Microsoft', '365', 'Subscription', '–', 'Special', 'Offer', 'for', 'Our', 'Learners', 'রিমাইন্ডার', '📢', 'রিমাইন্ডার', '📢']
477

In [59]:
x = df['users'].value_counts()
x.head()

users
group_notification    35
+880 1711-720153      15
+880 1751-087380       6
Excel 365              4
Shagor Vaia            2
Name: count, dtype: int64

In [60]:
df.tail(5)

,users,messages,month,day,hour,minute
57,+880 1711-720153,রিমাইন্ডার 📢,September,22,19,54
58,+880 1751-087380,"আসসালামু আলাইকুম, আশা করি সবাই ভালো আছেন। আপনা...",September,23,11,45
59,Excel 365,📢 Microsoft 365 Subscription – Special Offer f...,September,25,11,44
60,+880 1711-720153,রিমাইন্ডার 📢,September,26,14,37
61,+880 1711-720153,রিমাইন্ডার 📢,September,26,19,51

In [61]:
df.to_csv(r'./data.csv')

In [62]:
import os
print(os.getcwd())

/content

In [63]:
from google.colab import files
files.download('/content/data.csv')